---
- name: Ensure prereqs are installed
  ansible.builtin.apt:
    name: ca-certificates
    state: present 

- name: Register release codename
  ansible.builtin.shell: 
    cmd: '(. /etc/os-release && echo "$VERSION_CODENAME")'
  register: release_codename

- name: Register architecture
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  register: arch

- name: Ensure Docker's GPG key is installed
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Ensure Docker's APT repo is installed
  ansible.builtin.template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: '0644'

- name: Ensure Docker and related packages are installed
  ansible.builtin.apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
