---
- name: Privileged user is set up 
  become: true
  remote_user: debian
  hosts: kicksecure_docker_hosts
  roles:
    - ../roles/privileged-user
- name: Default admins are disabled/removed
  become: true
  remote_user: "{{ lookup('env', 'ADMIN_USERNAME') }}"
  hosts: kicksecure_docker_hosts
  roles:
    - ../roles/remove-default-admin-users
